<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('article')->insert([
            'title' => "Aurelia Aurita",
            'contentId' => "Aurelia aurita (juga dikenal dengan ubur-ubur bulan) adalah spesies yang dipelajari secara luas dari genus Aurelia. Semua spesies dalam genus saling berkaitan erat, dan sulit untuk mengidentifikasi medusa Aurelia tanpa pengambilan sampel genetik, sebagian besar apa yang berlaku sama bagi semua spesies dalam genus. Ubur-ubur ini tampak tembus pandang, biasanya berukuran sekitar 25-40 cm, dan dapat diidentifikasi oleh empat gonad berbentuk tapal kuda, mudah dilihat melalui bagian atas bel. Ubur-ubur ini makan dengan mengumpulkan medusa, plankton, dan moluska dengan tentakelnya, dan membawa mangsanya ke dalam tubuh untuk dicerna. Ubur-ubur ini hanya mampu bergerak terbatas, dan hanyut dengan arus, bahkan ketika berenang. Genus Aurelia ditemukan di hampir seluruh lautan di dunia, dari daerah tropis ke utara sejauh 70°LU dan ke selatan sejauh 40°LS. Spesies Aurelia aurita yang ditemukan di sepanjang pantai Atlantik timur Eropa Utara dan pantai Atlantik barat Amerika Utara di New England dan Kanada Timur. Secara umum, Aurelia hidup di perairan pantai yang dapat ditemukan di muara sungai dan pelabuhan. Ia hidup dalam suhu air laut berkisar dari 6°C hingga 31 °C, dengan suhu optimum 9 °C hingga 19 °C. A. aurita lebih menyukai laut sedang dengan arus yang konsisten. Spesies ini telah ditemukan di perairan dengan kadar garam serendah 6 bagian per seribu.

            Hubungan antara hipoksia musim panas dan distribusi ubur-ubur bulan yang menonjol selama bulan-bulan musim panas (Juli dan Agustus) di mana suhu tinggi dan kadar oksigen terlarut yang rendah. Dari tiga kondisi lingkungan yang diuji, bahwa kadar oksigen terlarut bawah memiliki efek paling signifikan pada kelimpahan ubur-ubur bulan. Kelimpahan tertinggi ubur-ubur bulan terjadi ketika konsentrasi oksigen terlarut bawah lebih rendah dari 2,0 mg L -1. Ubur-ubur bulan menunjukkan toleransi yang kuat pada kondisi oksigen terlarut yang rendah, yang mengapa populasi mereka masih relatif tinggi selama bulan-bulan musim panas. Umumnya, hipoksia menyebabkan spesies untuk bergerak dari zona tanpa oksigen, namun hal ini tidak terjadi pada ubur-ubur bulan. Selanjutnya, tingkat kontraksi bel yang menunjukkan aktivitas makan ubur-ubur bulan, tetap konstan meskipun konsentrasi oksigen terlarut lebih rendah dari normal. Selama bulan Juli dan Agustus teramati bahwa agregasi ubur-ubur bulan dari 250 individu yang dikonsumsi sekitar 100% dari biomassa mesozooplankton di Laut Pedalaman Seto. Predator ikan besar lainnya yang juga hadir di perairan pantai ini tampaknya tidak menunjukkan toleransi tinggi yang sama untuk konsentrasi oksigen terlarut yang rendah. Memakan dan kinerja predator ikan ini secara signifikan menurun ketika konsentrasi oksigen terlarut sangat rendah. Hal ini memungkinkan terjadinya persaingan rendah antara ubur-ubur bulan dan predator ikan lainnya atas zooplankton. Konsentrasi oksigen terlarut yang rendah di perairan pesisir seperti Teluk Tokyo di Jepang dan Laut Pedalaman Seto terbukti menguntungkan bagi ubur-ubur bulan dalam hal makanan, pertumbuhan, dan kelangsungan hidup.",
            'contentEn' => "Aurelia aurita (also called the common jellyfish, moon jellyfish, moon jelly or saucer jelly) is a species of the genus Aurelia. All species in the genus are very similar, and it is difficult to identify Aurelia medusae without genetic sampling; most of what follows applies equally to all species of the genus.

            The jellyfish is almost entirely translucent, usually about 25-40 cm (10-16 in) in diameter, and can be recognized by its four horseshoe-shaped gonads, easily seen through the top of the bell. It feeds by collecting medusae, plankton, and mollusks with its tentacles, and bringing them into its body for digestion. It is capable of only limited motion, and drifts with the current, even when swimming. The species Aurelia aurita is found in the North, Black, Baltic and Caspian Seas, Northeast Atlantic, Greenland, northeastern USA and Canada, Northwest Pacific and South America. In general, Aurelia is an inshore genus that can be found in estuaries and harbors.

            Aurelia aurita lives in ocean water temperatures ranging from 6-31 °C (43-88 °F); with optimum temperatures of 9-19 °C (48-66 °F). It prefers temperate seas with consistent currents. It has been found in waters with salinity as low as 6 parts per thousand. The relation between summer hypoxia and moon jellyfish distribution is prominent during the summer months of July and August where temperatures are high and dissolved oxygen (DO) is low. Of the three environmental conditions tested, bottom DO has the most significant effect on moon jellyfish abundance. Moon jellyfish abundance is the highest when bottom dissolved oxygen concentration is lower than 2.0 mg L-1. Moon jellyfish show a strong tolerance to low DO conditions, which is why their population is still relatively high during the summer. Generally, hypoxia causes species to move from the oxygen depleted zone, but this is not the case for the moon jellyfish. Furthermore, bell contract rate, which indicates moon jellyfish feeding activity, remains constant although DO concentrations are lower than normal. During July and August, it is observed that moon jellyfish aggregations of 250 individuals consumed an estimated 100% of the mesozooplankton biomass in the Seto Inland Sea. Other major fish predators that are also present in these coastal waters do not seem to show the same high tolerance to low DO concentrations that the moon jellyfish exhibit. The feeding and predatory performance of these fish significantly decreases when DO concentrations are so low. This allows for less competition between the moon jellyfish and other fish predators for zooplankton. Low DO concentrations in coastal waters such as Tokyo Bay in Japan and the Seto Inland Sea prove to be advantageous for the moon jellyfish in terms of feeding, growth, and survival.",
            'editor' => "Init"
        ]);
    }
}
